version: '3'
services:

  tomcat:
    build: bank-tomcat
    image: bank-tomcat
    ports:
     - "8080:8080"
     - "8000:8000"
    environment:
      JPDA_ADDRESS: 8000
      JPDA_TRANSPORT: dt_socket
      JPDA_SUSPEND: "y"
    depends_on:
     - postgres
    links:
     - postgres
    volumes:
     - ../bank-ws/target/bank-ws.war:/usr/local/tomcat/webapps/bank-ws.war
     - ./bank-tomcat/postgresql-42.0.0.jar:/usr/local/tomcat/lib/postgresql-42.0.0.jar
     - ./bank-tomcat/setenv.sh:/usr/local/tomcat/bin/setenv.sh
     - ./bank-tomcat/application.properties:/usr/local/tomcat/conf/application.properties
    command:
      catalina.sh jpda run

  postgres:
    build: bank-postgres
    image: bank-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./bank-postgres/bank.sql:/docker-entrypoint-initdb.d/bank.sql
    ports:
      - "5432:5432"
